services:
  # mongo:
  #   image: mongo:latest
  #   container_name: quizlo-mongo
  #   restart: unless-stopped
  #   ports:
  #     - "27020:27017"
  #   # environment:
  #   #   - MONGO_INITDB_ROOT_USERNAME=admin
  #   #   - MONGO_INITDB_ROOT_PASSWORD=password
  #   volumes:
  #     - mongo-data:/data/db
  #   healthcheck:
  #     test: echo 'db.runCommand("ping").ok' | mongosh mongodb://127.0.0.1:27017 --quiet
  #     interval: 2s
  #     timeout: 3s
  #     retries: 5
  #   networks:
  #     - rivals

  server:
    image: server:${TAG:-latest}
    container_name: quizlo-server
    build:
      context: ./server/
      dockerfile: Dockerfile.dev
    command: npm run dev
    volumes:
      - ./server/src:/home/node/server/src
    ports:
      - "3004:8080"
      - "3005:8081"
    environment:
      - PORT=8080
      - WS_PORT=8081
      - MONGODB_URI=mongodb://quizlo-mongo:27017/quiz
      - JWT_SECRET=rival-secret
      - SECRET_SALT=rival-salt
      - ALLOW_API_ACCESS=http://localhost:3003,http://localhost:3000
    networks:
      - rivals
    # depends_on:
    #   mongo:
    #     condition: service_healthy
    #     restart: true

  web:
    image: web:${TAG:-latest}
    container_name: quizlo-web
    build:
      context: ./web/
      dockerfile: Dockerfile.dev
    command: npm run dev
    volumes:
      - ./web/src:/home/node/root/src
    ports:
      - "3003:8080"
    environment:
      - PORT=8080
      - API_URL=http://localhost:3004
      - WS_URL=ws://localhost:3005
    networks:
      - rivals

networks:
  rivals:
    driver: bridge

volumes:
  node_modules:
  mongo-data:
    driver: local
