name: quizlo-prod
services:
  db:
    image: mongo:latest
    container_name: quizlo-db
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongodb://127.0.0.1:27017 --quiet
      interval: 2s
      timeout: 3s
      retries: 5
    networks:
      - server

  server:
    image: dshamak/quizlo-server:${TAG:-latest}
    container_name: quizlo-server
    build:
      context: ./server/
      dockerfile: Dockerfile.prod
    command: npm start
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - PORT=8080
      - WS_PORT=8081
      - JWT_SECRET=quizlo-secret
      - SECRET_SALT=quizlo-salt
      - MONGODB_URI=mongodb://quizlo-db:27017/region_1
 #     - ALLOW_API_ACCESS=http://localhost,http://localhost:80,http://127.0.0.1:80,http://127.0.0.1:8080
    networks:
      - server
    depends_on:
      db:
        condition: service_healthy
        restart: true

  web:
    image: dshamak/quizlo-web:${TAG:-latest}
    container_name: quizlo-web
    build:
      context: ./web/
      dockerfile: Dockerfile.prod
    command: npm start
    ports:
      - "80:8080"
    environment:
      - PORT=8080
      - SERVER_API_URL=http://quizlo-server:8080
    #   - API_URL=http://localhost:4001
    #   - WS_URL=ws://localhost:4002
    networks:
      - web
      - server

networks:
  server:
  web:

volumes:
  node_modules:
  mongo-data:
    driver: local
