name: quizlo-prod
services:
  api:
    image: dshamak/quizlo-server:${TAG:-latest}
    container_name: api
    build:
      context: ./server/
      dockerfile: Dockerfile.prod
    command: npm start
    ports:
      - "443"
      - "80"
      - "8080"
    env_file: .env
    environment:
      - WS_PORT=8080
      - JWT_SECRET=quizlo-secret
      - SECRET_SALT=quizlo-salt
    networks:
      - api

  web:
    image: dshamak/quizlo-web:${TAG:-latest}
    container_name: web
    build:
      context: ./web/
      dockerfile: Dockerfile.prod
    command: npm start
    ports:
      - "443"
      - "80"
    env_file: .env
    environment:
      - API_SERVICE=api
    networks:
      - web
      - api
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl/:/etc/ssl
    depends_on:
      - api
      - web
    networks:
      - api
      - web

networks:
  api:
  web:

volumes:
  node_modules:
