name: quizlo-local
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27020:27017"
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=admin
    #   - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongodb://127.0.0.1:27017 --quiet
      interval: 2s
      timeout: 3s
      retries: 5
    networks:
      - api-local

  api-local:
    image: server:${TAG:-latest}
    container_name: api-local
    build:
      context: ./
      dockerfile: ./server/Dockerfile.dev
    env_file:
      - .env
    command: npm run dev
    volumes:
      - ./server/src:/www/src
      - ./server/public:/www/public
      - ./shared:/shared
    ports:
      - "80"
      - "8080"
    environment:
      - NODE_ENV=development
      - PORT=80
      - WS_PORT=8080
      - REGION=region0
      - MONGODB_URI=mongodb://mongo:27017
      - JWT_SECRET=quizlo-secret
      - SECRET_SALT=quizlo-salt
      - ALLOW_API_ACCESS=http://localhost:3003
    networks:
      - api-local
    depends_on:
      mongo:
        condition: service_healthy
        restart: true

  web-local:
    image: web:${TAG:-latest}
    container_name: web-local
    build:
      context: ./
      dockerfile: ./web/Dockerfile.dev
    command: npm run dev
    volumes:
      - ./web/app:/www/app
      - ./web/src:/www/src
      - ./shared:/shared
    ports:
      - "80"
    environment:
      - NODE_ENV=development
      - PORT=80
      - API_SERVICE=api-local
      - WS_PORT=8080
    networks:
      - web-local
      - api-local

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx-local.conf:/etc/nginx/nginx.conf
    depends_on:
      - api-local
      - web-local
    networks:
      - api-local
      - web-local

networks:
  api-local:
  web-local:

volumes:
  node_modules:
  mongo-data:
    driver: local
