name: quizlo
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27020:27017"
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=admin
    #   - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongodb://127.0.0.1:27017 --quiet
      interval: 2s
      timeout: 3s
      retries: 5
    networks:
      - server

  server:
    image: server:${TAG:-latest}
    container_name: api
    build:
      context: ./server/
      dockerfile: Dockerfile.dev
    command: npm run dev
    volumes:
      - ./server/src:/www/src
    ports:
      - "3004:8080"
      - "3005:8081"
    environment:
      - NODE_ENV=development
      - PORT=8080
      - WS_PORT=8081
      - REGION=local
      - MONGODB_URI=mongodb://mongo:27017
      - JWT_SECRET=quizlo-secret
      - SECRET_SALT=quizlo-salt
      - ALLOW_API_ACCESS=http://localhost:3003,http://localhost:8080,http://127.0.0.1:3003,http://127.0.0.1:8080
    networks:
      - server
    depends_on:
      mongo:
        condition: service_healthy
        restart: true

  web:
    image: web:${TAG:-latest}
    container_name: web
    build:
      context: ./web/
      dockerfile: Dockerfile.dev
    command: npm run dev
    volumes:
      - ./web/app:/www/app
      - ./web/src:/www/src
    ports:
      - "3003:8080"
    environment:
      - NODE_ENV=development
      - PORT=8080
      - WS_PORT=3005
      - API_PORT=3004
      - SERVER_API_URL=http://api:8080
      - API_URL=http://localhost:3004
      - WS_URL=ws://localhost:3005
    networks:
      - web
      - server

networks:
  quizlo:
  server:
  web:

volumes:
  node_modules:
  mongo-data:
    driver: local
