events {
  worker_connections 1024;  # Maximum number of simultaneous connections that a worker process can handle
}

http {
  server {
    listen 80;
    server_name localhost;

	  location /api {
      rewrite ^/api(/.*)$ $1 break;
      proxy_pass http://api-local:80;
    }

    location /ws {
      proxy_pass http://api-local:8080;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_set_header Host $host;
    }

    location / {
      proxy_pass http://web-local:80;
    }
  }
}