events {
  worker_connections 1024;  # Maximum number of simultaneous connections that a worker process can handle
}

http {
  server {
    listen 80;
    server_name localhost dshamak.xyz 142.93.101.17;

    location / {
      return 301 https://$host$request_uri;
    }
  }

  server {
    listen 443 ssl;
    server_name localhost dshamak.xyz 142.93.101.17;

    ssl_certificate /etc/ssl/certificate.crt;
	ssl_certificate_key /etc/ssl/certificate.key;
	ssl_trusted_certificate /etc/ssl/bundle.crt;

    location /api {
      rewrite ^/api(/.*)$ $1 break;
      proxy_pass http://api:80;
    }

    location / {
      proxy_pass http://web:80;
    }
  }
}