FROM node:22 AS deps

RUN mkdir /www
WORKDIR /www/

COPY package.json index.ts tsconfig.json ./
COPY ./src ./src

RUN npm install
RUN npm run build

FROM node:22 AS runner
RUN mkdir /www
WORKDIR /www/
COPY --from=deps /www/node_modules ./node_modules
COPY --from=deps /www/dist ./
COPY package.json ./
# COPY ../ssl ./ssl

EXPOSE 80 443 8080
CMD [ "npm", "start" ]
