FROM node:22 AS deps

RUN mkdir /www
WORKDIR /www/

COPY ./server/package.json ./server/index.ts ./server/tsconfig.json ./server/esbuild.config.js ./
COPY ./server/src ./src
COPY ./shared /shared

RUN npm install
RUN npm run build

FROM node:22 AS runner
RUN mkdir /www
WORKDIR /www/

COPY ./server/public/ ./public
COPY --from=deps /www/node_modules ./node_modules
COPY --from=deps /www/dist ./
COPY ./server/package.json ./

EXPOSE 80 443 8080
CMD [ "npm", "start" ]
