name: Deploy to Droplet
on:
  repository_dispatch:
    types:
      - on-build-success
  workflow_run:
    workflows:
      - Build And Push
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy-to-droplet:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSH client
        run: sudo apt-get install -y openssh-client

      - name: SSH into Droplet, pull image, and run container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_SSH_HOST }}
          username: ${{ secrets.DROPLET_SSH_USERNAME }}
          key: ${{ secrets.DROPLET_SSH_PRIVATE_KEY }}
          port: ${{ secrets.DROPLET_SSH_PORT }}
          passphrase: ${{ secrets.DROPLET_SSH_PASSPHRASE }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_SERVER_REPO }}
            docker stop quizlo-server || true
            docker rm quizlo-server || true
            docker pull ${{ secrets.DOCKERHUB_WEB_REPO }}
            docker stop quizlo-web || true
            docker rm quizlo-web || true
            docker compose down || true
            docker compose up -d
          # docker run -d --name quizlo-server --network host -p 8081:8080 ${{ secrets.DOCKERHUB_SERVER_REPO }}
