name: Deploy to Droplet
on:
  workflow_run:
    workflows: ["Build And Push"]
    types:
      - completed
  workflow_dispatch:
    inputs:
      root_directory:
        description: "Directory where docker-compose.yml is located"
        required: true
        default: "/root"

jobs:
  deploy-to-droplet:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSH client
        run: sudo apt-get install -y openssh-client

      - name: Delete existing docker-compose.yml on the server (if exists)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_SSH_HOST }}
          username: ${{ secrets.DROPLET_SSH_USERNAME }}
          key: ${{ secrets.DROPLET_SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.DROPLET_SSH_PASSPHRASE }}
          port: ${{ secrets.DROPLET_SSH_PORT }}
          script: |
            if [ -f "${{ github.event.inputs.root_directory }}/.env" ]; then
              echo "Deleting existing .env file..."
              rm -f "${{ github.event.inputs.root_directory }}/.env"
            fi

            if [ -f "${{ github.event.inputs.root_directory }}/docker-compose.yml" ]; then
              echo "Deleting existing docker-compose.yml..."
              rm -f "${{ github.event.inputs.root_directory }}/docker-compose.yml"
            fi

      - name: Copy docker-compose.yml to the droplet
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DROPLET_SSH_HOST }}
          username: ${{ secrets.DROPLET_SSH_USERNAME }}
          key: ${{ secrets.DROPLET_SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.DROPLET_SSH_PASSPHRASE }}
          port: ${{ secrets.DROPLET_SSH_PORT }}
          source: ./docker-compose.yml
          target: ${{ github.event.inputs.root_directory }}
      

      - name: Copy ssl to the droplet
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DROPLET_SSH_HOST }}
          username: ${{ secrets.DROPLET_SSH_USERNAME }}
          key: ${{ secrets.DROPLET_SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.DROPLET_SSH_PASSPHRASE }}
          port: ${{ secrets.DROPLET_SSH_PORT }}
          source: ./ssl
          target: ${{ github.event.inputs.root_directory }}
      
      - name: Copy nginx.conf to the droplet
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DROPLET_SSH_HOST }}
          username: ${{ secrets.DROPLET_SSH_USERNAME }}
          key: ${{ secrets.DROPLET_SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.DROPLET_SSH_PASSPHRASE }}
          port: ${{ secrets.DROPLET_SSH_PORT }}
          source: ./nginx.conf
          target: ${{ github.event.inputs.root_directory }}

      - name: SSH into Droplet, pull image, and run container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_SSH_HOST }}
          username: ${{ secrets.DROPLET_SSH_USERNAME }}
          key: ${{ secrets.DROPLET_SSH_PRIVATE_KEY }}
          port: ${{ secrets.DROPLET_SSH_PORT }}
          passphrase: ${{ secrets.DROPLET_SSH_PASSPHRASE }}
          script: |
            # Navigate to the root directory
            cd ${{ github.event.inputs.root_directory }} || { echo "Error: Directory ${{ github.event.inputs.root_directory }} does not exist"; exit 1; }

            # Split input into lines and write to .env file
            echo "Creating .env file..."
            echo "${{ secrets.ENV_VARS }}" | tr ';' '\n' > .env

            # Confirm the contents of the .env file
            echo "Generated .env file contents:"
            cat .env

            # Check if docker-compose.yml exists
            if [ ! -f "docker-compose.yml" ]; then
              echo "Error: docker-compose.yml not found in directory ${{ github.event.inputs.root_directory }}" >&2
              exit 1
            fi
            # Pull Database
            # docker pull ${{ secrets.DOCKERHUB_DB_REPO }}
            # docker stop quizlo-db || true
            # docker rm quizlo-db || true
            # Pull Server
            docker pull ${{ secrets.DOCKERHUB_SERVER_REPO }}
            docker stop quizlo-server || true
            docker rm quizlo-server || true
            # Pull Web
            docker pull ${{ secrets.DOCKERHUB_WEB_REPO }}
            docker stop quizlo-web || true
            docker rm quizlo-web || true
            # Run containers
            docker compose down || true
            docker compose --env-file .env up -d || exit 1
