name: Restart Containers
on:
  workflow_dispatch:
    inputs:
      root_directory:
        description: "Directory where docker-compose.yml is located"
        required: true
        default: "/root"
      restart_api:
        description: "Restart api (yes / no)?"
        required: true
        default: "no"
      restart_web:
        description: "Restart web (yes / no)?"
        required: true
        default: "no"

jobs:
  restart-containers:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH client
        run: sudo apt-get install -y openssh-client

      - name: Define ROOT_DIRECTORY
        run: echo "ROOT_DIRECTORY=${{ github.event.inputs.root_directory || '/root' }}" >> $GITHUB_ENV

      - name: SSH into Droplet, restart containers
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_SSH_HOST }}
          username: ${{ secrets.DROPLET_SSH_USERNAME }}
          key: ${{ secrets.DROPLET_SSH_PRIVATE_KEY }}
          port: ${{ secrets.DROPLET_SSH_PORT }}
          passphrase: ${{ secrets.DROPLET_SSH_PASSPHRASE }}
          script: |
            ROOT_DIRECTORY="${{ env.ROOT_DIRECTORY }}" 
            RESTART_API="${{ inputs.restart_api }}"
            RESTART_WEB="${{ inputs.restart_web }}"
            # Navigate to the root directory
            cd $ROOT_DIRECTORY || { echo "Error: Directory $ROOT_DIRECTORY does not exist"; exit 1; }

            # Check if docker-compose.yml exists
            if [ ! -f "docker-compose.yml" ]; then
              echo "Error: docker-compose.yml not found in directory $ROOT_DIRECTORY" >&2
              exit 1
            fi

            if [ "$RESTART_API" = "yes" ] && [ "$RESTART_WEB" = "yes" ]; then
              docker compose up -d
              exit 0
            fi

            if [ "$RESTART_API" = "yes" ]; then
              echo "Restarting API..."
              docker compose up -d api
            fi

            if [ "$RESTART_WEB" = "yes" ]; then
              echo "Restarting web..."
              docker compose up -d web
            fi
