FROM node:22.9.0 AS deps

RUN mkdir /www

WORKDIR /www/

COPY package.json tsconfig.json postcss.config.js tailwind.config.ts remix.config.js vite.config.ts ./
COPY ./app/ ./app
COPY ./assets/ ./assets
COPY ./src/ ./src

RUN npm install
RUN npm run build

FROM node:22.9.0 AS runner
RUN mkdir /www
WORKDIR /www/
COPY --from=deps /www/node_modules ./node_modules
COPY --from=deps /www/build/ ./build
COPY ./public/ ./public
COPY package.json ./deploy/ ./
COPY ../ssl ./ssl

EXPOSE 8080
CMD [ "npm", "start" ]
