FROM node:22.9.0

RUN mkdir /www

WORKDIR /www/

COPY ./web/package.json ./web/tsconfig.json ./web/postcss.config.js ./web/tailwind.config.ts ./web/remix.config.js ./web/vite.config.ts ./
COPY ./web/app/ ./app
COPY ./web/assets/ ./assets
COPY ./web/src/ ./src

ENV CHOKIDAR_USEPOLLING=true

RUN npm install

EXPOSE 80
