FROM node:22.9.0 AS deps

RUN mkdir /www
RUN mkdir /shared

COPY ./shared /shared

WORKDIR /www/

COPY ./web/package.json ./web/tsconfig.json ./web/postcss.config.js ./web/tailwind.config.ts ./web/remix.config.js ./web/vite.config.ts ./
COPY ./web/app/ ./app
COPY ./web/assets/ ./assets
COPY ./web/src/ ./src

RUN npm install
RUN npm run build

FROM node:22.9.0 AS runner
RUN mkdir /www
WORKDIR /www/
COPY --from=deps /www/node_modules ./node_modules
COPY --from=deps /www/build/ ./build
COPY ./web/public/ ./public
COPY ./web/package.json ./web/deploy/ ./

EXPOSE 443 80
CMD [ "npm", "start" ]
