FROM node:22.9.0

RUN mkdir /www

WORKDIR /www/

COPY package.json tsconfig.json postcss.config.js tailwind.config.ts remix.config.js vite.config.ts ./
COPY ./app/ ./app
COPY ./assets/ ./assets
COPY ./src/ ./src

RUN npm install

EXPOSE 80
